apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-tesing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-tesing
  template:
    metadata:
      labels:
        app: nginx-tesing
    spec:
      containers:
        - name: nginx
          image: liquid07/k8s-ha:9c209c340a05b25cfd6d2bef3bccc142792c3d29
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-tesing
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx-tesing
